name: mishamosher_tiktoken
description: Tiktoken is a BPE tokeniser for use with OpenAI's models. It exposes APIs used for processing text using tokens.
homepage: https://mishamosher.com
repository: https://github.com/mishamosher/flutter_tiktoken
issue_tracker: https://github.com/mishamosher/flutter_tiktoken/issues?q=is%3Aissue+is%3Aopen+
version: 1.0.0

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  assets:
    - lib/tokens/cl100k_base/
    - lib/tokens/gpt2/
    - lib/tokens/p50k_base/
    - lib/tokens/r50k_base/
    - lib/tokens/o200k_base/
